apiVersion: types.kubefed.io/v1beta1
kind: FederatedAddon
metadata:
  name: nifi
  namespace: nifi
spec:
  placement:
    clusterSelector: {}
  template:
    apiVersion: kubeaddons.mesosphere.io/v1beta1
    kind: Addon
    metadata:
      annotations:
        appversion.kubeaddons.mesosphere.io/nifi: 1.9.4
        catalog.kubeaddons.mesosphere.io/addon-revision: 1.9.4-1
        catalog.kubeaddons.mesosphere.io/origin-repository: https://github.com/millerjem/kubeaddons-enterprise
        catalog.kubeaddons.mesosphere.io/origin-repository-version: master
        values.chart.helm.kubeaddons.mesosphere.io/nifi: https://raw.githubusercontent.com/cetic/helm-nifi/master/values.yaml
      labels:
        kubeaddons.mesosphere.io/name: nifi
      name: nifi
    spec:
      chartReference:
        chart: stable/nifi
        values: |
          ---
          master:
            useSecurity: false
            installPlugins:
              - prometheus:2.0.6
              - kubernetes:1.18.2
              - workflow-job:2.33
              - workflow-aggregator:2.6
              - credentials-binding:1.19
              - git:3.11.0
            csrf:
              defaultCrumbIssuer:
                enabled: false
                proxyCompatability: false
            serviceType: "ClusterIP"
            nifiUriPrefix: "/nifi"
            ingress:
              enabled: true
              path: /nifi
              annotations:
                kubernetes.io/ingress.class: traefik
        version: 1.9.4