---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: nifi
  labels:
    kubeaddons.mesosphere.io/name: nifi
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.12.1-1"
    appversion.kubeaddons.mesosphere.io/nifi: "1.12.1"
    values.chart.helm.kubeaddons.mesosphere.io/nifi: "https://raw.githubusercontent.com/cetic/helm-nifi/master/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.16.3
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: nifi
    repo: https://artifacthub.io/packages/helm/cetic/nifi
    version: 1.12.1
    values: |
      ---
      master:
        useSecurity: false
        installPlugins:
          - prometheus:2.0.6
          - kubernetes:1.18.2
          - workflow-job:2.33
          - workflow-aggregator:2.6
          - credentials-binding:1.19
          - git:3.11.0
        csrf:
          defaultCrumbIssuer:
            enabled: false
            proxyCompatability: false
        serviceType: "ClusterIP"
        nifiUriPrefix: "/nifi"
        ingress:
          enabled: true
          path: /nifi
          annotations:
            kubernetes.io/ingress.class: traefik
